---

- meta: flush_handlers

- name: Wait for Jenkins to be available
  shell: curl -s -o /dev/null -I -w "%{http_code}" http://localhost:{{ jenkins_extra_port }}
  register: resp
  until: resp.stdout.find("200") != -1
  retries: 10
  delay: 10

- include: ssh-creds.yml

- include: aws-creds.yml

- include: job-creds.yml
