---

- meta: flush_handlers

- name: Wait for Jenkins to be available
  uri: url="http://localhost:{{ jenkins_extra_port }}"
  register: resp
  until: resp.status|default(false) == 200
  retries: 10
  delay: 10

- include: ssh-creds.yml

- include: aws-creds.yml

- include: job-creds.yml

- include: shell-config.yml
